### ISSUE TITLE
Fill in LICENSE details with company / author info

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne-template#58]
See fields wrapped in `<...>` in [LICENSE](https://github.com/thehyve/delphyne-template/blob/master/LICENSE) file. Make sure to use consistent info with `delphyne` repo.

**Comment by alepev** [comment]
..or simply copy over the one from `delphyne`?

**Comment by Spayralbe** [comment]
> ..or simply copy over the one from `delphyne`?

Let's do that 👍

**Comment by alepev** [comment]
I added it to the changes in the `cleanup` bundle, I was just wondering how is it so short compared to the previous version 🤔
